organization: Natan FOURIÉ EIRL
defaultSticker: cl8p9eem9629909kycm8gkafb
stickers:
  -
    id: cl8p9eem9629909kycm8gkafb
    alias: hacktoberfest-2022-registered
  -
   id: cla3qeh72120908mppm4t7dgp
   alias: hacktoberfest-2022-level-4
  -
   id: cla3qe9bp105308mp12ty479d
   alias: surfer-moby-dock
  -
   id: clarpdd11082308jl4uo3euvl
   alias: appwrite-hacktoberfest-2022
